name: Vue3 Ionic publish
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'develop'
jobs:
  app-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn run build
      - uses: JS-DevTools/npm-publish@v1
        if: ${{ github.repository.name == 'teamsite-app' }}
        with:
          dry-run: true
          token: ${{ secrets.NPM_TOKEN }}
          package: package.json
